[[plugins]]
repo = 'shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'powershell -File install.ps1'
#hook_add = '''
#let g:LanguageClient_serverCommands = {}
#    let g:LanguageClient_serverCommands = {
#        \ 'rust': ['rustup', 'run', 'stable', 'rls'],
#        \ 'go': ['go-langserver', '-format-tool', 'gofmt', '-lint-tool', 'golint']
#        \ }
#
#" use completion
#set completefunc=LanguageClient#complete
#
#function LC_maps()
#  if has_key(g:LanguageClient_serverCommands, &filetype)
#    nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<CR>
#    nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
#  endif
#endfunction
#autocmd FileType * call LC_maps()
#'''

